"""Run every bench over every candidate x load and write the results table.

    python tb/run.py                 # everything
    python tb/run.py ac              # one bench
    python tb/run.py ac miller_ota   # one bench, one candidate

Writes out/results.json and docs/results.md. Nothing here decides a
topology -- the table is the input to that decision, not the decision.
"""
import json
import sys
from pathlib import Path

from common import TOPOLOGIES, VARIANTS, LOADS, OUT, ROOT, VDD
from benches import BENCHES

SPEC = {                    # console audio front-end targets, docs/spec.md
    "a_lf_db": (">=", 60.0),
    "ugf_hz": (">=", 2e6),
    "pm_deg": (">=", 60.0),
    "psrr_1k_db": (">=", 40.0),
    "slew_v_per_us": (">=", 0.1),
}


def fmt(v, unit=""):
    if v is None:
        return "--"
    if isinstance(v, float):
        if v != v:
            return "nan"
        if abs(v) >= 1e6:
            return f"{v/1e6:.3g} M{unit}"
        if abs(v) >= 1e3:
            return f"{v/1e3:.3g} k{unit}"
        return f"{v:.3g}{(' ' + unit) if unit else ''}"
    return str(v)


def main():
    which = sys.argv[1] if len(sys.argv) > 1 else None
    only = sys.argv[2] if len(sys.argv) > 2 else None
    benches = [which] if which else list(BENCHES)
    topos = [only] if only else TOPOLOGIES

    results = {}
    if (OUT / "results.json").exists():      # merge, so single-bench runs
        try:                                  # can be re-run in isolation
            results = json.loads((OUT / "results.json").read_text())
        except ValueError:
            results = {}

    for topo in topos:
        results.setdefault(topo, {})
        for load in LOADS:
            results[topo].setdefault(load, {})
            for b in benches:
                print(f"--- {b:5s} {topo:11s} {load}", flush=True)
                r = BENCHES[b](topo, load)
                results[topo][load][b] = r
                if b == "op":
                    bad = [i for i, d in r["devices"].items()
                           if not (d["sat_margin"] > 0)]
                    print(f"    isupply {fmt(r['isupply'])}A  "
                          f"vout {fmt(r['vout'])}V  "
                          f"out-of-saturation: {bad or 'none'}", flush=True)
                else:
                    print("    " + "  ".join(
                        f"{k}={fmt(v)}" for k, v in r.items()
                        if not isinstance(v, dict)), flush=True)

    (OUT / "results.json").write_text(json.dumps(results, indent=1,
                                                 default=str))
    write_report(results)
    print(f"\nwrote {OUT/'results.json'}")


def check(key, val):
    if key not in SPEC or val is None or val != val:
        return ""
    op, tgt = SPEC[key]
    ok = val >= tgt if op == ">=" else val <= tgt
    return " PASS" if ok else " **FAIL**"


def biased_ok(res, t, ld):
    """Is the output actually sitting at its bias point? If not, every
    small-signal number in that row is measured around a rail and means
    nothing -- say so instead of tabulating it."""
    op = res.get(t, {}).get(ld, {}).get("op") or {}
    v = op.get("vout")
    try:
        return abs(float(v) - 0.9) < 0.15
    except (TypeError, ValueError):
        return True     # no op data -> don't claim anything


def write_report(res):
    L = ["# Results - candidate audio-buffer topologies\n",
         "Generated by `python tb/run.py`. sky130 `tt` models, "
         f"{VDD} V, 25 C. Rows whose DC output is not at mid-rail are "
         "marked NOT BIASED - their AC numbers are not meaningful.\n",
         "Candidates (`tb/common.py`):\n"]
    for k, (sub, ib) in VARIANTS.items():
        L.append(f"- **{k}** - `spice/{sub}.sp`, external bias sink "
                 f"{ib*1e6:.0f} uA")
    L.append("\nLoads:\n")
    for k, v in LOADS.items():
        L.append(f"- **{k}** - {v['desc']}")

    L.append("\n## Small-signal / AC\n")
    L.append("| candidate | load | gain @1 Hz | A@20 kHz | UGF | phase margin | "
             "gain margin | PSRR@1 kHz |")
    L.append("|---|---|---|---|---|---|---|---|")
    for t in res:
        for ld in res[t]:
            ac = res[t][ld].get("ac") or {}
            ps = res[t][ld].get("psrr") or {}
            if not biased_ok(res, t, ld):
                L.append(f"| {t} | {ld} | _NOT BIASED_ | | | | | |")
                continue
            L.append(
                f"| {t} | {ld} | {fmt(ac.get('a_lf_db'),'dB')}"
                f"{check('a_lf_db', ac.get('a_lf_db'))} "
                f"| {fmt(ac.get('a_20k_db'),'dB')} "
                f"| {fmt(ac.get('ugf_hz'),'Hz')}"
                f"{check('ugf_hz', ac.get('ugf_hz'))} "
                f"| {fmt(ac.get('pm_deg'),'deg')}"
                f"{check('pm_deg', ac.get('pm_deg'))} "
                f"| {fmt(ac.get('gm_db'),'dB')} "
                f"| {fmt(ps.get('psrr_1k_db'),'dB')}"
                f"{check('psrr_1k_db', ps.get('psrr_1k_db'))} |")

    L.append("\n## Large-signal / DC\n")
    L.append("| candidate | load | I_supply | V_out(quiescent) | "
             "slew (worse edge) | rise | fall | settle 0.1 % | overshoot "
             "| gain error |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for t in res:
        for ld in res[t]:
            op = res[t][ld].get("op") or {}
            tr = res[t][ld].get("tran") or {}
            note = "" if biased_ok(res, t, ld) else " _(not biased)_"
            L.append(
                f"| {t} | {ld} | {fmt(op.get('isupply'),'A')} "
                f"| {fmt(op.get('vout'),'V')}{note} "
                f"| {fmt(tr.get('slew_v_per_us'),'V/us')}"
                f"{check('slew_v_per_us', tr.get('slew_v_per_us'))} "
                f"| {fmt(tr.get('slew_rise_v_per_us'),'V/us')} "
                f"| {fmt(tr.get('slew_fall_v_per_us'),'V/us')} "
                f"| {fmt(tr.get('tsettle_us'),'us')} "
                f"| {fmt(tr.get('overshoot_pct'),'%')} "
                f"| {fmt(tr.get('gain_err_pct'),'%')} |")

    L.append("\n## Operating point (line load)\n")
    for t in res:
        op = (res.get(t, {}).get("line") or {}).get("op")
        if not op:
            continue
        L.append(f"### {t}\n")
        L.append("| device | model | D/G/S | I_D | gm | gds | V_dsat | "
                 "V_ds | sat. margin |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for inst, d in op["devices"].items():
            nodes = d["nodes"]
            if isinstance(nodes, str):        # json round-trip
                nodes = eval(nodes)           # tuple literal from repr
            flag = "" if d["sat_margin"] > 0 else " **LINEAR**"
            L.append(f"| x{inst} | `{d['model'].split('__')[-1]}` "
                     f"| {'/'.join(nodes)} | {fmt(d['id'],'A')} "
                     f"| {fmt(d['gm'],'S')} | {fmt(d['gds'],'S')} "
                     f"| {fmt(d['vdsat'],'V')} | {fmt(d['vds'],'V')} "
                     f"| {fmt(d['sat_margin'],'V')}{flag} |")
        L.append("")

    p = Path(ROOT / "docs" / "results.md")
    p.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {p}")


if __name__ == "__main__":
    main()
