"""Compensation sweep for miller_ota: Cc x Rz against the primary load.

The kickoff run came back with 26 deg of phase margin and 32 % overshoot
at Cc = 2 pF, Rz = 2 k. That is a tuning result, not a topology result --
comparing an untuned two-stage amp against a single-stage one would be
comparing against a strawman. This sweep finds where the two-stage
candidate actually lands so the topology review argues about topology.

    python tb/sweep_comp.py [load]        # default: line

Writes docs/compensation.md.
"""
import sys
from pathlib import Path

from common import ROOT
from benches import bench_ac, bench_tran

CC = [2e-12, 4e-12, 8e-12, 16e-12]
# Rz starts at 100 ohm, not 0: ngspice clamps a zero-value resistor to
# 1e-12 ohm, and the resulting 1e12 S entry wrecks the matrix -- the
# sweep came back with -137 dB of gain, which is a conditioning failure
# wearing the costume of a circuit result.
RZ = [100.0, 2e3, 5e3, 10e3, 20e3]
PM_TARGET, UGF_TARGET = 60.0, 2e6


def main():
    load = sys.argv[1] if len(sys.argv) > 1 else "line"
    rows = []
    for cc in CC:
        for rz in RZ:
            params = f"pcc={cc:.4g} prz={rz:.6g}"
            tag = f"_cc{cc*1e12:.0f}p_rz{rz/1e3:.0f}k"
            ac = bench_ac("miller_ota", load, params=params, tag_extra=tag)
            tr = bench_tran("miller_ota", load, params=params, tag_extra=tag)
            row = dict(cc=cc, rz=rz, **ac, **tr)
            rows.append(row)
            print(f"Cc={cc*1e12:5.1f}p Rz={rz/1e3:5.1f}k  "
                  f"A={ac.get('a_lf_db', float('nan')):6.1f}dB  "
                  f"UGF={(ac.get('ugf_hz') or 0)/1e6:7.2f}MHz  "
                  f"PM={ac.get('pm_deg') or float('nan'):6.1f}deg  "
                  f"OS={tr.get('overshoot_pct', float('nan')):6.2f}%  "
                  f"SR={tr.get('slew_v_per_us', float('nan')):5.2f}V/us",
                  flush=True)

    ok = [r for r in rows
          if (r.get("pm_deg") or 0) >= PM_TARGET
          and (r.get("ugf_hz") or 0) >= UGF_TARGET]
    ok.sort(key=lambda r: -(r.get("ugf_hz") or 0))

    L = [f"# Miller compensation sweep (`{load}` load)\n",
         "Generated by `python tb/sweep_comp.py`. Targets: phase margin "
         f">= {PM_TARGET:.0f} deg and UGF >= {UGF_TARGET/1e6:.0f} MHz "
         "(`docs/spec.md` rows 7-8).\n",
         "| Cc | Rz | gain @1 Hz | UGF | phase margin | overshoot | slew |",
         "|---|---|---|---|---|---|---|"]
    def g(r, k, scale=1.0, unit="", fmt=".2f"):
        v = r.get(k)
        if v is None or v != v:
            return "--"
        return f"{v*scale:{fmt}} {unit}".strip()

    for r in rows:
        star = " **<--**" if ok and r is ok[0] else ""
        L.append(f"| {r['cc']*1e12:.0f} pF | {r['rz']/1e3:.0f} k "
                 f"| {g(r, 'a_lf_db', 1, 'dB', '.1f')} "
                 f"| {g(r, 'ugf_hz', 1e-6, 'MHz')} "
                 f"| {g(r, 'pm_deg', 1, 'deg', '.1f')} "
                 f"| {g(r, 'overshoot_pct', 1, '%')} "
                 f"| {g(r, 'slew_v_per_us', 1, 'V/us')} |{star}")
    L.append("")
    if ok:
        b = ok[0]
        L.append(f"**Best point meeting both targets:** Cc = "
                 f"{b['cc']*1e12:.0f} pF, Rz = {b['rz']/1e3:.0f} k -> "
                 f"UGF {b['ugf_hz']/1e6:.2f} MHz, PM {b['pm_deg']:.1f} deg, "
                 f"overshoot {b.get('overshoot_pct', float('nan')):.2f} %.")
    else:
        L.append("**No point meets both targets.** The two-stage candidate "
                 "cannot simultaneously hit the UGF and phase-margin rows "
                 "of the spec at this bias with these device sizes -- which "
                 "is a result for the review, not a tuning failure to hide: "
                 "the escape routes are more current in the output stage "
                 "(higher gm2 moves the second pole out) or relaxing the "
                 "UGF target, which row 6 of the spec ties to distortion.")
    p = Path(ROOT / "docs" / "compensation.md")
    p.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"\nwrote {p}")


if __name__ == "__main__":
    main()
